### ISSUE TITLE
Single Web Page For Repository 

### ISSUE THREAD

**Issue by pranjay-poddar** [pranjay-poddar/Data-Structures-And-Algorithms#128]
A single responsive web page in HTML, CSS, and JS with hacktoberfest poster, project admin details and contact links, repository details (issues, comits, contributors count, live closed PR counts) and hacktoberfest links.

**Comment by rohan26062001** [comment]
I would like to contribute, please assign this to me

**Comment by pranjay-poddar** [comment]
@rohan26062001 keep all the related files in a folder name web_page in root directory.(make a new folder)

Go ahead..All the best!

**Comment by rohan26062001** [comment]
Sure

**Comment by rohan26062001** [comment]
Please check, I'm done with my work
